---
title: "Ideas"
bibliography: references.bib
csl: ../citation_style.csl
format:
  html:
    fig-width: 8
    fig-height: 5
    theme: default
html-math-method:
  method: katex
---

Heteroscedastic GPs [@Griffiths:2023] chapter 6.

Gibbs kernel [@Rasmussen:2006] chapter 4 pg 93.

Applications of Bayesian optimisation [@Reiker2021] & [@Yang2022]

Gaussian processes.

Deep dive into quasi-random sequences.

A deep dive into MLE in Gaussian processes regression. In the posts, we tacitly assume a flat prior on kernel parameters causing the posterior to be proportional to the likelihood, which is why we can use MLE to find kernel parameters. A post could go multiple ways. We could discuss MLE for GPs and TPs, focusing on the prior assumptions. We could also discuss model selection from a set of kernels. BOptBook chapter 4.

Student's t processes. Or sampling from a multivariate Student's t distribution. [@Hofert2013]


```{r}
#' Random Samples from a Multivariate Student's t Distribution
#' 
#' @param n number of samples to sample
#' @param mu the mean of each input dimension
#' @param sigma the covariance matrix
#' @param nu degrees of freedom
#' @param epsilon numerical tolerance added to the diagonal of the covariance
#'  matrix. This is necessary for the Cholesky decomposition, in some cases.
#'
#' @return numerical vector of n samples
rmvst <- function(n = 1, mu, sigma, nu, epsilon = 1e-6) {
  p <- length(mu)
  if (!all(dim(sigma) == c(p, p))) stop("incompatible dimensions of arguments")
  ev <- eigen(sigma, symmetric = TRUE)$values
  if (!all(ev >= -epsilon * abs(ev[1L]))) {
    stop("The covariance matrix (sigma) is not positive definite")
  }
  cholesky <- chol(sigma + diag(p) * epsilon)
  standard_normal_samples <- matrix(rnorm(n * p), ncol = p)
  chi_samples <- sqrt(nu / rchisq(n, df = nu))
  t_samples <- sweep(standard_normal_samples, 1, chi_samples, FUN = `*`)
  sweep(t_samples %*% cholesky, 2, mu, FUN = `+`)
}
```


# References {-}

<div id="refs"></div>

# License

The content of this project itself is licensed under the [Creative Commons Attribution-ShareAlike 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/), and the underlying code is licensed under the [GNU General Public License v3.0 license](https://github.com/AnHosu/bespoke-bayesian-biochem/blob/main/LICENSE).
